// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpCGTQbOW9b9HiR4ZpDZ802ilYFi0OvX4',
    appId: '1:250052247093:web:30b563910a904168733b7c',
    messagingSenderId: '250052247093',
    projectId: 'glucowizard',
    authDomain: 'glucowizard.firebaseapp.com',
    storageBucket: 'glucowizard.appspot.com',
    measurementId: 'G-Z5XCDP0R04',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBUYVBPI1z-jwW-Ie63gj1DInDsIM47ME',
    appId: '1:250052247093:android:a5424d57eb73d5b9733b7c',
    messagingSenderId: '250052247093',
    projectId: 'glucowizard',
    storageBucket: 'glucowizard.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlLukAv6CiT8yDwNFf4bgGiSk3K5c56ok',
    appId: '1:250052247093:ios:6daf5cf73be8562b733b7c',
    messagingSenderId: '250052247093',
    projectId: 'glucowizard',
    storageBucket: 'glucowizard.appspot.com',
    iosClientId: '250052247093-q3jssqpb7q9ch09etftee5dc0gmq0ms4.apps.googleusercontent.com',
    iosBundleId: 'com.example.glucowizardFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlLukAv6CiT8yDwNFf4bgGiSk3K5c56ok',
    appId: '1:250052247093:ios:6daf5cf73be8562b733b7c',
    messagingSenderId: '250052247093',
    projectId: 'glucowizard',
    storageBucket: 'glucowizard.appspot.com',
    iosClientId: '250052247093-q3jssqpb7q9ch09etftee5dc0gmq0ms4.apps.googleusercontent.com',
    iosBundleId: 'com.example.glucowizardFlutter',
  );
}
